### ISSUE TITLE
Feature request: Automagic raffling

### ISSUE THREAD

**Issue by dnyvik** [capgemini-stavanger/CapRaffle#11]
Winservice that does the actual raffling and sends out emails to winners when the deadline has passed.

**Comment by stigrune** [comment]
Add a new datetime in the database event table.

**Comment by arneaase** [comment]
Any suggestions on how to approach this ?

suggestion:
1. Perform automatic raffle when the deadline has passed
2. Let everyone choose "their" replay of the drawing (flipbox, flightboard, normal etc)
3. 2-3 hours after the deadline, display winners in a normal table

This suggestion makes it possible to do something special with the drawing (ie use flipbox in the cafebar etc) and it removed some of the administration away from the event creator.

Any other suggestions on how to solve this ?

**Comment by dnyvik** [comment]
I think its easier to differentiate these scenarios by letting the event creator choose whether he/she wants to enable automagic raffling for his/her event. The creator then has the option of doing the raffling on a big screen if he/she so chooses. Automagic raffling could then just be an update of the database and an email to the winner and creator of the event.

**Comment by arneaase** [comment]
Implemented dnyvik's suggestion
