### ISSUE TITLE
Feature request: "Don't accept less than *x* tickets" option

### ISSUE THREAD

**Issue by khellang** [capgemini-stavanger/CapRaffle#32]
Allow participants to specify that they only want at least _x_ tickets, otherwise, the tickets will be automatically rejected and given to someone else. This would be ideal for participants who wants to bring a friend or their partner to an event, but don't want to go alone.

**Comment by stigrune** [comment]
It would probably be best if this is the default setting? Participants can specify that they are willing to accept only 1 ticket in event or maybe in user settings ?
