### ISSUE TITLE
Send email about event when there are no winners/participants after deadline

### ISSUE THREAD

**Issue by dnyvik** [capgemini-stavanger/CapRaffle#39]
As the creator of an event
I would like to receive email when automagic raffling occurs and are no winners/participants
So that I can take the appropriate measures to ensure that the tickets are used by someone.

**Comment by khellang** [comment]
As stated in #38 - this seems to be implemented already. See NotifyCreator in EmailSender...

**Comment by dnyvik** [comment]
How nice =)

**Comment by khellang** [comment]
But that doesn't mean it works ;P

**Comment by dnyvik** [comment]
Cock

**Comment by dnyvik** [comment]
=)
