### ISSUE TITLE
Importing events to outlook -> wrong start date.

### ISSUE THREAD

**Issue by dnyvik** [capgemini-stavanger/CapRaffle#40]
I recently imported an event to outlook from the winner notification email and got a start date which was +1 hour.

**Comment by khellang** [comment]
Isn't this the same as issue #37?

**Comment by dnyvik** [comment]
Well why isn't it fixed then?!? Hehe, no sorry didn't see the other issue...

**Comment by khellang** [comment]
I have fixed it and sent a pull request :)

**Comment by dnyvik** [comment]
Just call yourself  awseomessprime from now on! =)
